# Classifying Penguins with Keras

In [14]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn import preprocessing
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

In [15]:
! pip install palmerpenguins
from palmerpenguins import load_penguins
penguins = load_penguins()
penguins.head()


,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007


In [16]:
penguins_x = pd.concat([penguins[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm']], pd.get_dummies(penguins['sex'])], axis = 1)
# penguins_x = penguins_x[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'female', 'male']]
penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,3750.0,39.1,18.7,181.0,False,True
1,3800.0,39.5,17.4,186.0,True,False
2,3250.0,40.3,18.0,195.0,True,False
3,NaN,NaN,NaN,NaN,False,False
4,3450.0,36.7,19.3,193.0,True,False
...,...,...,...,...,...,...
339,4000.0,55.8,19.8,207.0,False,True
340,3400.0,43.5,18.1,202.0,True,False
341,3775.0,49.6,18.2,193.0,False,True
342,4100.0,50.8,19.0,210.0,False,True


In [17]:
x = penguins_x.values
min_max_scaler = preprocessing.MinMaxScaler()
scaled_penguins_x = pd.DataFrame(min_max_scaler.fit_transform(x), columns=penguins_x.columns)
scaled_penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,0.291667,0.254545,0.666667,0.152542,0.0,1.0
1,0.305556,0.269091,0.511905,0.237288,1.0,0.0
2,0.152778,0.298182,0.583333,0.389831,1.0,0.0
3,NaN,NaN,NaN,NaN,0.0,0.0
4,0.208333,0.167273,0.738095,0.355932,1.0,0.0
...,...,...,...,...,...,...
339,0.361111,0.861818,0.797619,0.593220,0.0,1.0
340,0.194444,0.414545,0.595238,0.508475,1.0,0.0
341,0.298611,0.636364,0.607143,0.355932,0.0,1.0
342,0.388889,0.680000,0.702381,0.644068,0.0,1.0


In [18]:
penguins_y = penguins['species']
print(penguins_y)
penguins_y = penguins_y.astype('category').cat.codes.to_numpy()
penguins_y

0         Adelie
1         Adelie
2         Adelie
3         Adelie
4         Adelie
         ...    
339    Chinstrap
340    Chinstrap
341    Chinstrap
342    Chinstrap
343    Chinstrap
Name: species, Length: 344, dtype: object


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [19]:
# Shuffle the data so all 3 species are mixed throughout
# Without this, the data is grouped by species (all Adelie first, then Gentoo, then Chinstrap)
# which causes the model to train poorly and produce nan loss values

penguins_combined = scaled_penguins_x.copy()
penguins_combined['target'] = penguins_y

# Drop rows with NaN values (2 rows in this dataset)
penguins_combined = penguins_combined.dropna()

# Shuffle with a fixed random_state so results are reproducible
penguins_combined = penguins_combined.sample(frac=1, random_state=42).reset_index(drop=True)

# Re-separate X and y after shuffle — both will now have 342 rows
scaled_penguins_x = penguins_combined.drop(columns=['target'])
penguins_y = penguins_combined['target'].values

print(f"Rows after shuffle and dropna: {scaled_penguins_x.shape[0]}")
print(f"Class distribution: {dict(zip(*[list(x) for x in __import__('numpy').unique(penguins_y, return_counts=True)]))}")
scaled_penguins_x.head()

Rows after shuffle and dropna: 342
Class distribution: {np.int8(0): np.int64(151), np.int8(1): np.int64(68), np.int8(2): np.int64(123)}


,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,0.527778,0.410909,0.154762,0.779661,1.0,0.0
1,0.298611,0.189091,0.880952,0.457627,0.0,1.0
2,0.333333,0.272727,0.904762,0.322034,1.0,0.0
3,0.472222,0.436364,0.785714,0.406780,0.0,1.0
4,0.444444,0.341818,0.619048,0.389831,0.0,1.0


In [20]:
#construct the model
inputs = keras.Input(shape=(6,))
x = layers.Dense(7, activation = 'relu')(inputs)
x = layers.Dense(5, activation = 'relu')(x)
x = layers.Dense(3, activation = 'relu')(x)
outputs = layers.Dense(3, activation='sigmoid')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model")

In [21]:
model.summary()

Model: "penguin_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 6)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 7)              │            49 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 5)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 3)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 119 (476.00 B)

 Trainable params: 119 (476.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
keras.utils.plot_model(model, show_shapes = True)

You must install graphviz (see instructions at https://graphviz.gitlab.io/download/) for `plot_model` to work.


In [23]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history = model.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs=100, validation_split=0.1)

scores = model.evaluate(scaled_penguins_x, penguins_y, verbose=2)

Epoch 1/100


/opt/anaconda3/envs/tf-ml/lib/python3.10/site-packages/keras/src/backend/tensorflow/nn.py:717: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.3583 - loss: 1.0743 - val_accuracy: 0.4000 - val_loss: 1.0754
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3616 - loss: 1.0623 - val_accuracy: 0.4000 - val_loss: 1.0654
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4007 - loss: 1.0543 - val_accuracy: 0.4286 - val_loss: 1.0569
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4495 - loss: 1.0472 - val_accuracy: 0.4286 - val_loss: 1.0485
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4463 - loss: 1.0403 - val_accuracy: 0.4286 - val_loss: 1.0407
Epoch 6/100


/opt/anaconda3/envs/tf-ml/lib/python3.10/site-packages/keras/src/backend/tensorflow/nn.py:717: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4788 - loss: 1.0329 - val_accuracy: 0.4286 - val_loss: 1.0329
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4919 - loss: 1.0260 - val_accuracy: 0.4286 - val_loss: 1.0247
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4886 - loss: 1.0184 - val_accuracy: 0.4286 - val_loss: 1.0164
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5342 - loss: 1.0105 - val_accuracy: 0.4571 - val_loss: 1.0069
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5309 - loss: 1.0025 - val_accuracy: 0.4571 - val_loss: 0.9976
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5570 - loss: 0.9940 - val_accuracy: 0.4857 - val_loss: 0.9879
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5668 - loss: 0.9856 - val_accuracy: 0.5143 - val_loss: 0.9786
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6059 - loss: 0.9764 - val_accuracy: 0.5143 - val_loss: 0.9682
Epoch 14

In [24]:
model_logit_true = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model_scaled")

model_logit_true.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_true = model_logit_true.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs = 100, validation_split = 0.1)

scores = model_logit_true.evaluate(scaled_penguins_x, penguins_y, verbose = 2)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8013 - loss: 0.5493 - val_accuracy: 0.8000 - val_loss: 0.5199
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5467 - val_accuracy: 0.8000 - val_loss: 0.5181
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5450 - val_accuracy: 0.8000 - val_loss: 0.5169
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5435 - val_accuracy: 0.8000 - val_loss: 0.5154
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5421 - val_accuracy: 0.8000 - val_loss: 0.5138
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5410 - val_accuracy: 0.8000 - val_loss: 0.5128
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5396 - val_accuracy: 0.8000 - val_loss: 0.5120
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.5384 - val_accuracy: 0.8000 - val_loss: 0.5105

In [25]:
model_logit_true.predict(scaled_penguins_x)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


array([[0.02284109, 0.02593094, 0.99967754],
       [0.70838207, 0.5173977 , 0.27782777],
       [0.70838207, 0.5173977 , 0.27782777],
       ...,
       [0.70838207, 0.5173977 , 0.27782777],
       [0.01586582, 0.0197293 , 0.99984   ],
       [0.70838207, 0.5173977 , 0.27782783]],
      shape=(342, 3), dtype=float32)

In [26]:
penguins['species']

0         Adelie
1         Adelie
2         Adelie
3         Adelie
4         Adelie
         ...    
339    Chinstrap
340    Chinstrap
341    Chinstrap
342    Chinstrap
343    Chinstrap
Name: species, Length: 344, dtype: object

In [ ]:
penguins_y

array([2, 0, 0, 0, 0, 1, 2, 2, 1, 0, 0, 2, 1, 2, 0, 2, 0, 0, 2, 0, 2, 0,
       1, 0, 0, 0, 0, 2, 0, 1, 2, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 0, 2, 2,
       0, 2, 1, 2, 0, 0, 2, 2, 2, 0, 0, 2, 0, 1, 1, 0, 2, 1, 1, 2, 2, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 2, 1, 0, 0, 2, 0, 1, 0, 0, 0, 1,
       0, 2, 2, 1, 2, 2, 2, 2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 2, 2, 2, 1, 2,
       0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 1, 0, 2, 1, 2, 2,
       2, 2, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2, 0, 1,
       1, 1, 2, 2, 1, 1, 2, 2, 0, 0, 1, 2, 2, 0, 1, 2, 0, 1, 1, 2, 1, 2,
       2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 2,
       2, 0, 1, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 2, 2,
       0, 0, 0, 2, 2, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 2, 2, 1, 2, 2, 0,
       2, 0, 0, 2, 0, 0, 2, 0, 0, 1, 0, 1, 2, 1, 0, 1, 2, 2, 1, 0, 0, 0,
       0, 0, 0, 0, 2, 0, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 0, 2,
       2, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 2, 0,